<a href="https://colab.research.google.com/github/nitinfaye/Electric-energy-prediction/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [13]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [12]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [14]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1))

### Compiling the ANN

In [9]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [10]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 970us/step - loss: 27762.4067
Epoch 2/100
240/240 [==============================] - 0s 977us/step - loss: 321.2744
Epoch 3/100
240/240 [==============================] - 0s 974us/step - loss: 297.6972
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 277.8018
Epoch 5/100
240/240 [==============================] - 0s 956us/step - loss: 240.8809
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 215.7505
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 184.2908
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 163.2543
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 136.1718
Epoch 10/100
240/240 [==============================] - 0s 985us/step - loss: 123.7805
Epoch 11/100
240/240 [==============================] - 0s 923us/step - loss: 100.4352
Epoch 12/100
240/240 [==============================] - 0s 1

### Predicting the results of the Test set

In [11]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.12 431.23]
 [462.08 460.01]
 [465.54 461.14]
 ...
 [472.84 473.26]
 [439.54 438.  ]
 [458.78 463.28]]
